name: BTest

on:
  pull_request:
  push:
    branches: [master]

jobs:
  Run-BTest:
    strategy:
      matrix:
        # Even though python-3.5 is EOL it is still the minimum Python version
        # required by Zeek so we should validate that our code works with it.
        #
        # Since that Python version is not available on ubuntu-22.04 (currently
        # ubuntu-latest), we run the Linux job on ubuntu-20.04 which still has
        # it.
        python-version: [3, 3.5]
        os: [macos-latest, ubuntu-20.04, windows-latest]

    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
            python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
            python -m pip install sphinx multiprocess
      - run: make test
